version: '3.8'

services:
  main:
    build: 
      context: ./main
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - microservice
    environment:
      - MICROSERVICE_URL=http://microservice:5050/
      - LOCALHOST_URL = http://localhost:5050/
      
  microservice:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    ports:
      - "5050:5050"