version: '1.0'
services:
  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - microservice
      
  microservice:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    ports:
      - "6000:6000"